import "./globals.css";

import Contexts from "./components/Contexts";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Body from "./components/Body";

export const metadata = {
  title: "Planet Peanut",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="dk">
      <Contexts>
        <Body>
          <Header />
          {children}
          <Footer />
        </Body>
      </Contexts>
    </html>
  );
}
