import "./globals.css";

import Header from "./components/Header";
import Footer from "./components/Footer";
import Body from "./components/Body";

export const metadata = {
  title: "Planet Peanut",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="dk">
      <Body>
        <Header />
        {children}
        <Footer />
      </Body>
    </html>
  );
}
